### ISSUE TITLE
redriver2 and syndicate frame rate drop

### ISSUE THREAD

**Issue by alireza109** [InspirationByte/eq2engine#1]
hi soapy man . i am big fan to your projects (redriver2 and driver syndicate ) . when i install driver syndicate , frame rate drop happened to me . my device is dell d830 . and i wish to play these games smoothly without problems . in redriver 2 when game is in full screen this issue occurs too .  and when game isn't in full screen frame rate increases . please solve this issue i really love driver game series .

**Comment by SoapyMan** [comment]
I can confirm that laptops do have an issue with severe frame rate dropping when it's not being charged, but I need further confirmation of this issue with the reproduction.
